/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        secondary: 'var(--color-secondary)',
        midnight_text: 'var(--color-midnight_text)',
        muted: 'var(--color-muted)',
        error: 'var(--color-error)',
        warning: 'var(--color-warning)',
        light_grey: 'var(--color-light_grey)',
        grey: 'var(--color-grey)',
        dark_grey: 'var(--color-dark_grey)',
        border: 'var(--color-border)',
        success: 'var(--color-success)',
        section: 'var(--color-section)',
        darkmode: 'var(--color-darkmode)',
        darklight: 'var(--color-darklight)',
        dark_border: 'var(--color-dark_border)',
        tealGreen: 'var(--color-tealGreen)',
        charcoalGray: 'var(--color-charcoalGray)',
        deepSlate: 'var(--color-deepSlate)',
        slateGray: 'var(--color-slateGray)',
      },
      maxWidth: {
        '8xl': 'var(--container-screen-xl)',
        '9xl': 'var(--container-screen-2xl)',
      },
      spacing: {
        '8xl': 'var(--spacing-8xl)',
        '25': 'var(--spacing-25)',
        '29': 'var(--spacing-29)',
        '45': 'var(--spacing-45)',
        '50': 'var(--spacing-50)',
        '51': 'var(--spacing-51)',
        '85': 'var(--spacing-85)',
        '94': 'var(--spacing-94)',
        '120': 'var(--spacing-120)',
        '6_25': 'var(--spacing-6_25)',
        '70%': 'var(--spacing-70%)',
        '40%': 'var(--spacing-40%)',
        '30%': 'var(--spacing-30%)',
        '80%': 'var(--spacing-80%)',
        '8_5': 'var(--spacing-8_5)',
        '3_75': 'var(--spacing-3_75)',
      },
      inset: {
        '5%': 'var(--inset-5%)',
        '35%': 'var(--inset-35%)',
      },
      zIndex: {
        1: 'var(--z-index-1)',
        2: 'var(--z-index-2)',
        999: 'var(--z-index-999)',
      },
      fontSize: {
        14: ['var(--text-14)', { lineHeight: 'var(--text-14--line-height)' }],
        16: ['var(--text-16)', { lineHeight: 'var(--text-16--line-height)' }],
        17: ['var(--text-17)', { lineHeight: 'var(--text-17--line-height)' }],
        18: ['var(--text-18)', { lineHeight: 'var(--text-18--line-height)' }],
        21: ['var(--text-21)', { lineHeight: 'var(--text-21--line-height)' }],
        22: ['var(--text-22)', { lineHeight: 'var(--text-22--line-height)' }],
        24: ['var(--text-24)', { lineHeight: 'var(--text-24--line-height)' }],
        28: ['var(--text-28)', { lineHeight: 'var(--text-28--line-height)' }],
        30: ['var(--text-30)', { lineHeight: 'var(--text-30--line-height)' }],
        36: ['var(--text-36)', { lineHeight: 'var(--text-36--line-height)' }],
        40: ['var(--text-40)', { lineHeight: 'var(--text-40--line-height)' }],
        44: ['var(--text-44)', { lineHeight: 'var(--text-44--line-height)' }],
        54: ['var(--text-54)', { lineHeight: 'var(--text-54--line-height)' }],
        70: ['var(--text-70)', { lineHeight: 'var(--text-70--line-height)' }],
        76: ['var(--text-76)', { lineHeight: 'var(--text-76--line-height)' }],
        86: ['var(--text-86)', { lineHeight: 'var(--text-86--line-height)' }],
      },
      backgroundImage: {
        'start': 'var(--background-image-start)',
        'perk': 'var(--background-image-perk)',
      },
      blur: {
        220: 'var(--blur-220)',
        400: 'var(--blur-400)',
      },
    },
  },
  plugins: [],
}; 